name: ObbyFillPlugin
version: 1.0
main: io.github.crackedbrew.obbyfillplugin.ObbyFillPlugin
description: A plugin that fills the players inventory with obsidian for a modifiable price
commands:
  obbyfill:
    description: right now adds money
    usage: /<command>
    permission: obbyfillplugin.command.obbyfill
    permission-message: You do not have permission to run this command
permissions:
  obbyfillplugin.command.obbyfill:
    description: Allows for the use of the ObbyFill command
    default: true